spring.application.name=InvcProj
spring.datasource.url=jdbc:postgresql://localhost:5432/Invoice
spring.datasource.username=postgres
spring.datasource.password=password
logging.level.org.springframework.security=DEBUG
spring.jpa.show-sql= true
spring.jpa.hibernate.ddl-auto=update
spring.resources.add-mappings=false
spring.datasource.driver-class-name=org.postgresql.Driver
spring.mvc.format.match-enum=true
debug=true
server.port=8080
spring.redis.host=localhost
spring.redis.port=6379
# spring.redis.password=your_password
spring.redis.database=0
spring.redis.lettuce.pool.max-active=10
spring.redis.lettuce.pool.max-idle=5
spring.cache.type=redis
spring.cache.redis.time-to-live=600000
spring.cache.redis.cache-null-values=false
license.key=ZWRpdGlvbj1CSUxMLU1JVFJBfGV4cGlyeT0yMDI2LTEyLTA0fGVtYWlsPWFkbWluQHB1cmVtb29udGVjaC5jb218Y3VzdG9tZXI9cHVyZW1vb24tdGVjaA==.HSK1+nqeN3D3Gq67ikRJU0AwklBUb9v1AivugX1nzuu0z6bzYjIYnb9dJQJDxzCPn+SF9riQfjHUxqhGQrSbcFmfspKvBx92GUDPFSxJMt7DQ47xP96Q7+WlM+1rjY2WW8Ly/TgAw+Vt6Zfc2zXqvzsnXpaBh5Q8Si5cNEAcKB7Mre8izKxAxOYGPdIqKGmJdoHv1VvXQmRWQ/fDr21LOSxqGBe5+oOwvsvMAvV/lM+LEcYOVV65ENUtP6CwcSMcZrvT5kn48oWUWogOXFqU36UHut910J2Lxzy0XFtyqauT91DhfSnP7PvHQXJZmbMYV8pv+BoEKZeGsjb8Be8Kag==
license.check-on-login=true
license.periodic-check-hours=24
license.warning-days=7
logging.level.org.springframework.web=INFO 
logging.level.com.example.invc_proj=INFO
logging.level.org.springframework=WARN
logging.level.org.hibernate.SQL=INFO
spring.rabbitmq.host: localhost
spring.rabbitmq.port: 5672
spring.rabbitmq.username: user
spring.rabbitmq.password: 123
invoice.pdf.base-dir=${user.home}/Desktop/invoices

